# Generated by Django 5.0.6 on 2024-05-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('information', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, max_length=2000, null=True)),
                ('instageram', models.URLField(blank=True, max_length=2000, null=True)),
                ('twiter', models.URLField(blank=True, max_length=2000, null=True)),
                ('linkdin', models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
