# Generated by Django 5.0.6 on 2024-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_apoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoinment',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
