# Generated by Django 5.0.6 on 2024-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_apoinment_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoinment',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
