# Generated by Django 5.0.6 on 2024-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_apoinment_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tretment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=100)),
                ('sort_information', models.TextField()),
                ('long_information', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='apoinment',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
