# Generated by Django 5.0.6 on 2024-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_tretment_alter_apoinment_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='benner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
